version: "3.7"
services:
  event-app:
    container_name: event-app
    build: ./app
    ports:
      - "3003:3000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
